### ISSUE TITLE
List of participants

### ISSUE THREAD

**Issue by ossybel** [Tolsi/vrf-lottery#2]
Hi Tolsi! How to be sure that lottery starter are using a full list of participants and not only few? For example there was 1k retwitts but starter can put in the file only three or ten... And will chose the winner from them.

**Comment by Tolsi** [comment]
Hi, Ossybel!

If the lottery starter didn’t use the entire list of participants, then if you get a full list of participants, using the proof of the organizer will not be successful. The check will pass only if the organizer publishes a list of several participants (not all). You will be able to verify it yourself using the proof that he did not use 1000, but 3-4 participants and nothing else. Using this you will be able to prove that the lottery starter cheated. 

Note that such a completely transparent list of participants is possible, for example, in the blockchain or on some forum, but not possible in the telegram (the list of participants is visible only to the bot contest owner) or twitter (you cannot get a definite list and number of subscribers or reposters). Often organizers have the right to edit the list of participants (delete bots or minors).

This utility cannot guarantee that the list of participants is correct. Therefore, in order to fully trust the lottery starter, the list of participants must be published before the height of the choice of the winner.
